name: Git Bisect Workflow

on: [push]

jobs:
  git-bisect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Nécessaire pour accéder à tout l'historique des commits

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set bad and good hashes
        run: |
          echo "BAD_HASH=<bad-hash>" >> $GITHUB_ENV
          echo "GOOD_HASH=<good-hash>" >> $GITHUB_ENV
        # Remplacez `<bad-hash>` et `<good-hash>` par les valeurs appropriées.

      - name: Run git bisect with Python script
        run: python myscript.py
